/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import database.JDBCUtill;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Haitaiba
 */
public class NguoiDungView extends javax.swing.JFrame {
        private String taiKhoan;
        private String matKhau;
    /**
     * Creates new form NguoiDungView
     */
    public NguoiDungView(String taiKhoan, String matKhau) {
        initComponents();
        this.taiKhoan = taiKhoan;
        this.matKhau = matKhau;
        setLocationRelativeTo(null);
        loadTen();
        loadDataToTable();
    }

    private NguoiDungView() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtThongTin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtThongTin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtThongTin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtThongTin.setText("Thông Tin Người Dùng");
        getContentPane().add(txtThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -3, 696, 80));

        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 80, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên phòng", "Đồ đạc", "SĐT", "Căn cước", "Tiền điện", "Tiền nước", "Tổng tiền", "Thanh toán"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 810, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nguoidung.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DangNhap dangNhap = new DangNhap();
        dangNhap.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void loadTen() {
            try {
                Connection con = JDBCUtill.getConnection();
                String sql = "SELECT hovaten\n"
                        + "FROM khachthue\n"
                        + "JOIN nguoidung  ON nguoidung.makhachthue = khachthue.makhachthue\n"
                        + "WHERE nguoidung.taikhoan = ? AND nguoidung.matkhau = ?;";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, taiKhoan);
                ps.setString(2, matKhau);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    String hoVaTen = rs.getString("hovaten");
                    txtThongTin.setText("Xin Chào:"+hoVaTen);
                }else{
                    JOptionPane.showMessageDialog(this, "Không tìm thấy tên người dùng!");
                }
                JDBCUtill.closeConnection(con);
            } catch (SQLException ex) {
                Logger.getLogger(NguoiDungView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Lỗi khi tải thông tin họ và tên.");
            }
    }
private void loadDataToTable() {
    try {
        Connection con = JDBCUtill.getConnection();
        String sql = "SELECT p.tenphong, p.dodac, k.sodienthoai, k.cccd, h.tiendien, h.tiennuoc, h.tienphong, h.tongtien, h.thanhtoan " +
                     "FROM nguoidung u " +
                     "JOIN khachthue k ON u.makhachthue = k.makhachthue " +
                     "JOIN phongtro p ON k.maphong = p.maphong " +
                     "JOIN hoadon h ON k.makhachthue = h.makhachthue " +
                     "WHERE u.taikhoan = ? AND u.matkhau = ?";
        
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, taiKhoan);
        ps.setString(2, matKhau);
        
        ResultSet rs = ps.executeQuery();
        
        // Định nghĩa các cột trong bảng
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);  // Xóa dữ liệu cũ trong bảng
        DecimalFormat formatter = new DecimalFormat("#,###");
        // Lặp qua các kết quả và thêm vào bảng
        while (rs.next()) {
            String tenPhong = rs.getString("tenphong");
            String doDac = rs.getString("dodac");
            String soDienThoai = rs.getString("sodienthoai");
            String cccd = rs.getString("cccd");
            String tienDien = formatter.format(rs.getDouble("tiendien"));
            String tienNuoc = formatter.format(rs.getDouble("tiennuoc"));
            String tienPhong = formatter.format(rs.getDouble("tienphong"));
            String tongTien = formatter.format(rs.getDouble("tongtien"));
            String thanhToan = rs.getString("thanhtoan");
            
            // Thêm một dòng vào bảng
            model.addRow(new Object[]{tenPhong, doDac, soDienThoai, cccd, tienDien, tienNuoc, tienPhong, tongTien, thanhToan});
        }
        
        JDBCUtill.closeConnection(con);
    } catch (SQLException ex) {
        Logger.getLogger(NguoiDungView.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu vào bảng.");
    }
}


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguoiDungView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguoiDungView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguoiDungView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguoiDungView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NguoiDungView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtThongTin;
    // End of variables declaration//GEN-END:variables
}
