/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import database.JDBCUtill;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author Haitaiba
 */
public class QuanLyPhongFrame extends javax.swing.JFrame {

    private JDBCUtill JDBCUtil;

    /**
     * Creates new form QuanLyPhongFrame
     */
    public QuanLyPhongFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JTextField();
        txtDoDac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbTrangThai = new javax.swing.JCheckBox();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Tên Phòng");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setText("Đồ đạc");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));
        getContentPane().add(txtTenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 100, -1));
        getContentPane().add(txtDoDac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 160, -1));

        jLabel4.setText("Đã thuê");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        cbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTrangThaiActionPerformed(evt);
            }
        });
        getContentPane().add(cbTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 40, -1));

        btThem.setText("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        getContentPane().add(btThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "Đồ Đạc", "Trạng Thái"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 160, 600, 240));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Quanlyphong.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleName("QuanLyPhong");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTrangThaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = JDBCUtil.getConnection();
            String sql = "INSERT INTO phongtro(tenphong,trangthai,dodac) VALUES (?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, txtTenPhong.getText());
            ps.setBoolean(2, cbTrangThai.isSelected());
            ps.setString(3, txtDoDac.getText());
            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                loadTableData(); // Cập nhật bảng
            }
            ps.close();
            JDBCUtil.closeConnection(con);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm dữ liệu: " + e.getMessage());
        }
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 phòng để xóa");
            return;
        }
        String maPhong = jTable1.getValueAt(row, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa dòng này");
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection con = JDBCUtill.getConnection();
                String sql = "DELETE FROM phongtro WHERE maphong = ?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, maPhong);
                int result = ps.executeUpdate();

                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa phòng thành công!");
                    loadTableData(); // Cập nhật bảng
                }
                ps.close();
                JDBCUtil.closeConnection(con);

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa phòng!" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        int row = jTable1.getSelectedRow(); // Lấy dòng được chọn
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một phòng để sửa!");
            return;
        }

        String maPhong = jTable1.getValueAt(row, 0).toString(); // Lấy mã phòng
        String tenPhong = txtTenPhong.getText();
        String doDac = txtDoDac.getText();
        boolean trangThai = cbTrangThai.isSelected(); // Checkbox cho trạng thái

        try {
            Connection con = JDBCUtill.getConnection();
            String sql = "UPDATE phongtro SET tenphong = ?, trangthai = ?, dodac = ? WHERE maphong = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, tenPhong);
            ps.setBoolean(2, trangThai);
            ps.setString(3, doDac);
            ps.setString(4, maPhong);

            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật phòng thành công!");
                loadTableData(); // Cập nhật bảng
            }
            ps.close();
            JDBCUtil.closeConnection(con);

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa phòng: " + ex.getMessage());
        }
    }//GEN-LAST:event_btSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear dữ liệu cũ trong bảng
        try {
            // Kết nối CSDL
            Connection con = JDBCUtill.getConnection();

            // Truy vấn dữ liệu
            String sql = "SELECT maphong, tenphong, trangthai, dodac FROM phongtro";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            // Duyệt kết quả và thêm vào model
            while (rs.next()) {
                String maPhong = rs.getString("maphong");
                String tenPhong = rs.getString("tenphong");
                String doDac = rs.getString("dodac");
                String trangThai = rs.getBoolean("trangthai") ? "Đã thuê" : "Chưa thuê";
                model.addRow(new Object[]{maPhong, tenPhong, doDac, trangThai});
            }

            rs.close();
            ps.close();
            JDBCUtil.closeConnection(con);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + ex.getMessage());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhongFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JCheckBox cbTrangThai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDoDac;
    private javax.swing.JTextField txtTenPhong;
    // End of variables declaration//GEN-END:variables
}
